### ISSUE TITLE
candidateBio.getDetailedBio() sometimes fails to return information in the "candidate" and "office" fields

### ISSUE THREAD

**Issue by jbullock35** [umatter/pvsR#3]
My research team has been using pvsR 0.3 and R 4.0.2. We're using `candidateBio.getBio()` to retrieve biographical information about candidates. It works well. But `candidateBio.getDetailedBio()` sometimes fails to return information that is provided by the Vote Smart API and that is available through `candidateBio.getBio()`. Specifically, calls to `candidateBio.getDetailedBio()`  sometimes return a list in which the "candidate" and "office" list-elements are empty (except for "candidateId").

Here is an example:
```
library(pvsR)
pvs.key <- yourKey
CandidateBio.getDetailedBio(candidateId = 26777)
```
As expected, the last command returns a list with seven elements: "candidate," "office," and so on. But the "candidate" element includes only the candidateId. It is missing firstName, lastName, birthPlace, etc. The "office" element includes candidateId, an NA value for "name," and nothing else.

The problem doesn't seem to lie with the API itself, as this URL retrieves all of the candidate and office information for the candidateId used in the example: http://api.votesmart.org/CandidateBio.getDetailedBio?key=[yourKey]&candidateId=26777. And the problem seems to affect 94 different members of the House in the 115th and 116th Congresses (2017-20). It affects some senators, too.

Is there a way to use pvsR to retrieve "candidate" and "office" information for these candidates from a call to `CandidateBio.getDetailedBio()`?

Thank you for any help that you can offer, and for a great package.

**Comment by umatter** [comment]
Thanks for pointing this out. I have just pushed a fix to resolve this issue. The following tests seem to work fine. Let me know if the problem persists.

```
devtools::install_github("umatter/pvsR")
library(pvsR)
CandidateBio.getDetailedBio(candidateId = 26777)
CandidateBio.getDetailedBio(candidateId = 26776)
CandidateBio.getDetailedBio(candidateId = 26775)
CandidateBio.getDetailedBio(candidateId = 15722)
```

**Comment by jbullock35** [comment]
Thank you. This is a big help -- the new version does seem to fix the problem that I mentioned.
