### ISSUE TITLE
use of rbind_all() leads to errors with recent versions of dplyr

### ISSUE THREAD

**Issue by jbullock35** [umatter/pvsR#4]
I am using R 4,0.2, dplyr 1.0.2, and the just-released version of pvsR 0.4, https://github.com/umatter/pvsR/commit/b04b6dcce563660182cc31951583bead92813eb5, that fixes issue #3. This new version has some trouble with certain calls to `Candidates.getByOfficeState()`, and perhaps with certain calls to other commands. For example,
```
Candidates.getByOfficeState(  # call to Vote Smart API
  stateId      = c("CA", "NY"), 
  officeId     = 5,  # House members
  electionYear = 2016,
  all          = TRUE)
```
produces this error message: `Error in rbind_all(output.list) : could not find function "rbind_all"`. The problem arises in the previous version of pvsR, https://github.com/umatter/pvsR/commit/abfe5f49b8367d9c3135a6d919cd0b7127881a15, too. But it doesn't appear in the version on CRAN (v0.3, dated 2014-09-23).

The problem in recent versions seems to be that [dplyr no longer contains `rbind_all()`](https://github.com/tidyverse/dplyr/issues/4430).

**Comment by umatter** [comment]
Thanks a lot for reporting this! With the latest commit `rbind_all` has been replaced with `bind_rows`. Your example should now run through.

``` 
devtools::install_github("umatter/pvsR")
 Candidates.getByOfficeState(  # call to Vote Smart API
  stateId      = c("CA", "NY"), 
  officeId     = 5,  # House members
  electionYear = 2016,
  all          = TRUE)
```
Let me know if you encounter any issues with this fix.

**Comment by jbullock35** [comment]
Thank you—the new fix seems to work perfectly.

And thank you again for a great package.
