### ISSUE TITLE
feature request: check for PVS key with getOption() or getAnywhere()

### ISSUE THREAD

**Issue by jbullock35** [umatter/pvsR#5]
The package checks for the user's API key by looking for a `pvs.key` variable in the global environment. The strategy works under many conditions. But it doesn't work when one is using pvsR functions in a different environment. For example, it doesn't seem possible to use pvsR commands in a file that one sources with `sys.source()`—not unless one adds the `pvs.key` definition to the "master" file, where it typically won't belong. (The master file won't have pvsR commands; instead, they'll be collected into the file that is sourced with `sys.source()`.)

Here is an example:
```
library(pvsR)
pvs.key <- myKey
Elect_ID94 <- Election.getElectionByYearState(year = 1994)
```
This code will work under many conditions. But if you store it in file `myFile.R` and then run these commands in a clean R environment, it will fail:
```
pvs_environment <- new.env()
sys.source("myFile.R", envir = pvs_environment)
```
Specifically, it will fail with this error message:
```
Error in get("pvs.key", envir = .GlobalEnv) : object 'pvs.key' not found
```

The problem is that pvsR is looking for `pvs.key` in only the global environment. Can this behavior be changed?

One alternative would be to check for a user-defined "pvs.key" option. For example, users might run `options("pvs.key") <- myKey`, and thus be freed of the need to code the (somewhat sensitive) PVS key into each file. The key could then be retrieved with getOption(`pvs.key`).

Another option, less robust but easier to implement, would just be to replace `get("pvs.key", envir = .GlobalEnv)` with `getAnywhere("pvs.key")$objs[[1]]`.

Thank you again for a very helpful package.

**Comment by jbullock35** [comment]
Is it OK if I file a pull request to implement this feature? Specifically, the pvsR functions would check for a "pvs.key" option before searching the global environment for a "pvs.key" variable.

**Comment by umatter** [comment]
> Is it OK if I file a pull request to implement this feature? Specifically, the pvsR functions would check for a "pvs.key" option before searching the global environment for a "pvs.key" variable.

Sure, that would be great, thanks!

**Comment by jbullock35** [comment]
Thank you—I filed the pull request.

**Comment by umatter** [comment]
Thanks for contributing to the package! I've tested the changes and merged the pull request. As all features requested in this issue are covered with the merge, I close the issue.

**Comment by jbullock35** [comment]
Thank you—very glad to have this new feature.
